[project]
name = "plotter"
version = "0.1.0"
description = "Plot serial data in real time"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyqt6>=6.10.1",
    "pyqtgraph>=0.14.0",
    "pyserial>=3.5",
]
